  deploy-job:
    steps:
      - checkout
      - run:
          name: Run setup script
          command: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "19:ef:68:84:b3:86:34:54:8c:ca:25:02:ec:fe:3d:74"
      - run:
          name: Deploy Master to Heroku
          command:
            git push --force git@heroku.com:$HEROKU_APP_NAME.git HEAD:refs/heads/master
            heroku run npm run build
            heroku restart

  workflows:
    version: 2
    build-deploy:
      jobs:
       - build-job
       - deploy-job:
           requires:
             - build-job
           filters:
             branches:
               only: master
